name: qsann
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - cudensitymat-cu12==0.3.2
      - cupauliprop-cu12==0.1.0
      - cuquantum-cu12==25.11.0
      - custabilizer-cu12==0.1.0
      - custatevec-cu12==1.11.0
      - cutensor-cu12==2.4.1
      - cutensornet-cu12==2.10.0
      - dill==0.4.0
      - filelock==3.19.1
      - fire==0.7.1
      - fsspec==2025.9.0
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - ply==3.11
      - psutil==7.1.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - qiskit==2.2.3
      - qiskit-aer==0.14.2
      - qiskit-aer-gpu==0.14.2
      - qiskit-terra==0.45.3
      - rustworkx==0.17.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - stevedore==5.6.0
      - symengine==0.14.1
      - sympy==1.14.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tqdm==4.67.1
      - triton==2.3.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: /home/junyeollee/miniconda3/envs/qsann
